### ISSUE TITLE
24620226_Infografia_KarenIraisMontalvoReyes_1AS

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/infografia-KarenIMont#1]
[24620226_Infografía_KarenIraisMontalvoReyes_1AS.pdf](https://github.com/user-attachments/files/16743401/24620226_Infografia_KarenIraisMontalvoReyes_1AS.pdf)

**Comment by Proyect-A16** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:12/14
Referencias:13/14
Presentación:13/14
Calificación Final: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
